spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  zipkin:
    sender:
      type: rabbit
    service:
      name: order
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  cloud:
    stream:
      bindings:
        myMessageInput:
          group: order
          content-type: application/json
        myMessageOutput:
          group: order
          content-type: application/json
env: dev
girl:
  name: lili
  age: 22
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug