spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: 139.199.211.226
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
        myMessageInput:
          group: order
          content-type: application/json
        myMessageOutput:
          group: order
          content-type: application/json
env: dev
girl:
  name: lili
  age: 22
