spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
    service:
      name: product
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
env: dev
logging:
  level:
    org.springframework.cloud.openfeign: debug